version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./laravel:/work


  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: